### ISSUE TITLE
Add options to TableIOService API

### ISSUE THREAD

**Issue by imagejan** [scijava/scijava-table#11]
We need a new `TableIOService` that takes care of table-specific logic when opening/saving tables, such as how to deal with row and column headers etc.

See [this comment](https://gitter.im/scijava/scijava-common?at=5e7954c82e334e1b7af03fb5) by @ctrueden on gitter.

/cc @frauzufall

**Comment by frauzufall** [comment]
@imagejan [it exists](https://github.com/scijava/scijava-table/blob/master/src/main/java/org/scijava/table/io/TableIOService.java), we would just extend it, right? 

New method:
```
public Table<?, ?> open(String source, boolean readRowHeaders, boolean readColumnHeaders)
```
And there we would need to assign the parameters with something like [this method](https://github.com/scijava/scijava-plugins-io-table/blob/e09a9e06c73dde23ef474df33fa090cdbdf59966/src/test/java/org/scijava/table/DefaultTableIOPluginTest.java#L297-L310) or is there a more convenient way of setting the parameters of `IOPlugin`s? 

Happy to do the work if no one else has time and if what I just described sounds ok.

**Comment by frauzufall** [comment]
This [`setValues`](https://github.com/scijava/scijava-plugins-io-table/blob/e09a9e06c73dde23ef474df33fa090cdbdf59966/src/test/java/org/scijava/table/DefaultTableIOPluginTest.java#L297-L310) method could also become something like `setInputs(Plugin plugin, Object... inputs)` in the `PluginService`..

**Comment by imagejan** [comment]
We could probably get rid of the `@Parameter` annotations and refactor them into plain Java methods with suitable arguments. As `IOPlugin`s aren't `Module`s or `Command`s, the parameter annotations don't make much sense anyhow, do they?

> New method:
> `public Table<?, ?> open(String source, boolean readRowHeaders, boolean readColumnHeaders)`

Yes, and similar for `write`. Are there any other options we should respect when opening/writing table data in general? Like how to deal with incomplete rows/missing cells etc.?

**Comment by ctrueden** [comment]
> As `IOPlugin`s aren't `Module`s or `Command`s, the parameter annotations don't make much sense anyhow, do they?

They do make sense in that _any_ SciJava plugin with service parameters will have them injected when the plugin is instantiated via the `PluginService`. But indeed, their scope is more limited than with `Command`s, where you can utilize a wide range of object types.

**Comment by imagejan** [comment]
> They do make sense in that any SciJava plugin with service parameters

Yeah, no doubts about the services, sure.

I had those other 10 parameters of [`DefaultTableIOPlugin`](https://github.com/scijava/scijava-plugins-io-table/blob/e09a9e06c73dde23ef474df33fa090cdbdf59966/src/main/java/org/scijava/table/DefaultTableIOPlugin.java#L70-L116) in mind, that are not services.

Would it make sense to have *all* of those (4 `boolean`, 2 `String`, 2 `char`, 2 `Function`) accessible via some API in `TableIOService`?

**Comment by frauzufall** [comment]
I don't know how to pass these parameters from the `DefaultTableIOService` to the `DefaultTableIOPlugin` since it [does not address it directly](https://github.com/scijava/scijava-table/blob/master/src/main/java/org/scijava/table/io/DefaultTableIOService.java#L67).. Would it be too much of a stretch to introduce a `IOPlugin:open(final String source, Map<String, Object> parameters)` method or is there another way I'm not seeing right now?

**Comment by imagejan** [comment]
> Would it be too much of a stretch to introduce a IOPlugin:open(final String source, Map<String, Object> parameters) method

I'd like to hear @ctrueden's opinion about this, as it would involve changing the API in `scijava-common`.

Alternatively, we could create an `interface TableIOPlugin extends IOPlugin` that adds the required signatures specific to tables.

**Comment by frauzufall** [comment]
I like the `TableIOPlugin` solution a lot, it's less invasive and would also avoid dealing with string parameters..

**Comment by frauzufall** [comment]
I wrote a `TableIOPlugin` with an `open(final String source, boolean readColHeaders, boolean readRowHeaders, char separator)` method, but since the `DefaultTableIOPlugin` always loads tables as `String` by default, the `parser` should also be an option. This might need to be configurable per column? :-/ With all these parameters maybe a `TableIOOptions` class is better?

**Comment by imagejan** [comment]
Sorry for the lack of reply so far. Let's reconsider this with the new [`Options`](https://github.com/scijava/scijava-optional/blob/3f8fa41be5de9e7a5fc5423f6162deb810416eb2/src/main/java/org/scijava/optional/Options.java) from `scijava-optional`.

**Comment by frauzufall** [comment]
Added via https://github.com/scijava/scijava-table/commit/a3057947b0fb533b968ea77b3136694be0290721
