### ISSUE TITLE
Improving tests

### ISSUE THREAD

**Issue by frauzufall** [scijava/scijava-table#22]
I am working on [this issue to add options to TableIOService API](https://github.com/scijava/scijava-table/issues/11) which includes improving the `DefaultTableIOPlugin`. @imagejan pointed me to [the `setValues` method](https://github.com/scijava/scijava-plugins-io-table/blob/master/src/test/java/org/scijava/table/DefaultTableIOPluginTest.java#L297-L310) which adjusts the parameters of `DefaultTableIOPlugin` for the tests. 

I expected the tests should work without this hack to prove that the default values actually do something useful, but then 3/4 tests fail. 

It would be cool to simplify the tests to prove or disprove that `DefaultTableIOPlugin` is working correctly.

I have some issues with `GenericTable` which I would like to add tests for and fix them:
- a `GenericTable` with e.g. `Integer` values has `String` values after saving and loading
- the default parameters in `DefaultTableIOPlugin` are inconsistent - `writeRowHeaders` is true meaning row headers will be saved to disk, but `readRowHeaders` is false which makes them appear as data after saving and loading

Let me know if I should not work on this or if there is a reason for keeping the `setValues` method in the tests or if I misunderstood something.

**Comment by frauzufall** [comment]
The [default parser](https://github.com/scijava/scijava-plugins-io-table/blob/master/src/main/java/org/scijava/table/DefaultTableIOPlugin.java#L112) always returns `String`. Should it stay like this or should it guess the type?

**Comment by imagejan** [comment]
> Should it stay like this or should it guess the type?

I'd say auto-guessing the type would be preferable. With an `Options` parameter, we could also think of some way to explicitly defining the desired type per table column to be read. And the way how invalid/missing values should be handled.

I'm thinking of all the options in KNIME's CSV Reader node, for example. But that's maybe too much at once...

**Comment by imagejan** [comment]
As far as I can tell, the points discussed here were all addressed in https://github.com/scijava/scijava-plugins-io-table/pull/6, so I guess this can be closed. Please reopen if I'm wrong.
