### ISSUE TITLE
Consider supporting multi-index similar to pandas

### ISSUE THREAD

**Issue by imagejan** [scijava/scijava-table#6]
See https://github.com/imagej/pyimagej/issues/27#issuecomment-474589306.

**Comment by ctrueden** [comment]
Who needs this, and for what purpose? I am reluctant to complexify the SciJava table API.

**Comment by imagejan** [comment]
Just because @hadim said:
> Then we could have a 1:1 converter with Pandas.

But there no urgent need or use case. So let's close this, and reopen if/when a need arises.
