### ISSUE TITLE
Add TableIOService to read/write tables from locations

### ISSUE THREAD

**Issue by ctrueden** [scijava/scijava-table#7]
Similar to `DatasetIOService` for images, but type-safe for tables.

This will require some thought: do we want to hardcode a particular table I/O implementation in the service? Or do we need to create some new plugin type for tables, and then have a single `IOPlugin` implementation that delegates to the `TableIOService`. It's a bit tricky.

See also https://github.com/imagej/tutorials/pull/77#discussion_r344849596

**Comment by imagejan** [comment]
This should probably go to https://github.com/scijava/scijava-plugins-io-table where we already have an `IOPlugin` for table structures.

**Comment by ctrueden** [comment]
Yeah, this is what I was alluding to with "This will require some thought."

New services should not live in `*-plugins-*` components. The rule of thumb for the plugins components is that they always go at runtime scope. If the `TableIOService` lived there, you'd need compile scope in order to reference the interface.

The idea is that `TableIOService` would be a thin service that delegates to `IOService`. But somehow (see below) guarantees that the source is only opened if it would end up being a `Table`. And in this way, can provide type safety on the returned data.

A lazy way to guarantee would be to simply call `IOService#open` and check the return type and throw an exception if the data is the wrong type. But this is potentially very wasteful. It would be nice if we could fail faster than that.

So then a more industrious way would be to call `IOService#getOpener(source)` and check that the `getDataType()` of the returned `IOPlugin` is `Table` or a subtype thereof.
